name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set environment to test
        run: sed -i 's/#local/#test/' src/control-plane-core/constants.mo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        shell: bash
        run: bun i --frozen-lockfile

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "auto"

      - name: Setup DIDC
        shell: bash
        run: |
          # Get latest release tag using jq for robust JSON parsing
          export VERSION_DIDC=$(curl --silent "https://api.github.com/repos/dfinity/candid/releases/latest" \
            | jq -r '.tag_name')

          # Download and install
          wget https://github.com/dfinity/candid/releases/download/${VERSION_DIDC}/didc-linux64
          sudo mv didc-linux64 /usr/local/bin/didc
          sudo chmod +x /usr/local/bin/didc

      - name: Setup Mops
        uses: dfinity/setup-mops@v1

      - name: Install Mops Packages
        run: mops install

      - name: Build
        run: |
          dfx start --background
          dfx deploy
          dfx stop

      - name: Check Format
        run: bun run format:check

      - name: Lint Motoko
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/caffeinelabs/lintoko/releases/download/v0.7.0/lintoko-installer.sh | sh
          bun run lint

      - name: Test
        run: bun run test
